### ISSUE TITLE
Packaging / Installation instruction

### ISSUE THREAD

**Issue by batisteo** [anass-b/theme-kimbie-dark-fixed-vscode#1]
I'm pretty new to VSCode, I love Kimbie dark, and I guess you fixed what was annoying me!

But I have no clue how to install it. I don't find it within the extensions.

Thanks for the effort!

**Comment by anass-b** [comment]
@batisteo  Now I published it in Visual Studio Market Place: https://marketplace.visualstudio.com/items?itemName=anassb.theme-kimbie-dark-fixed

You can install it from within Visual Studio Code by searching for "Kimbie Dark Fixed" and installing it.

**Comment by batisteo** [comment]
Thank you!

Could you dim the color of whitespaces too? It would be great.

**Comment by anass-b** [comment]
@batisteo Could you please provide me with a screenshot of what you mean exactly by "whitespaces" ?

**Comment by anass-b** [comment]
@batisteo Would be also very helpful if you could create a new github issue for the whitespaces issue, so we can close this one.
