### ISSUE TITLE
Dimmed Whitespaces

### ISSUE THREAD

**Issue by batisteo** [anass-b/theme-kimbie-dark-fixed-vscode#2]
It would be nice to have also darker whitespaces (for the moment just spaces and tabs).
Something like 30% of whit it is now maybe?

![With Spaces](https://cloud.githubusercontent.com/assets/2727048/19418298/602f001a-93c1-11e6-9f3c-8efbff2ed114.png)

![With Tabs](https://cloud.githubusercontent.com/assets/2727048/19418320/dcde03e0-93c1-11e6-9da0-5abf0389b87c.png)

**Comment by anass-b** [comment]
@batisteo Fixed and published to Visual Studio Marketplace, you can now update your extension to get the changes

**Comment by batisteo** [comment]
Much better! Thanks a lot, and that was quick!
